### ISSUE TITLE
WebSocket

### ISSUE THREAD

**Issue by kislball** [Discordoo/discordoo#12]
This issue is created to track development of WS module for Discordoo.

- [x] Create a `Client#useGatewayProvider` method
  - [x] Thus, create a GatewayProvider delegate(API is tbd) 
- [x] Begin implementation of WebSocket connection
  - [x] Sharding(clustering **mustn't** be implemented by the module, just by wrapper or core)
  - [x] Compression
  - [x] Erlpack

**Comment by Mirdukkk** [comment]
websocket is almost fully ready
